Before-visit page
GSG-K3/urban-calendar pull request #57
Opened 2020-07-07 15:57 UTC by Jood80

### Content
- [ ] NavBar #48 
- [ ] Tabs #21 
- [ ] Questions:
   - [ ] What do you prefer for your visit to be
   - [ ] What are you interested in viewing today
   - [ ] Yes/No Question about Covid-19
- [ ] Back button
- [ ] Next button
---
- [ ] Front-end validation

2020-07-08 08:38 UTC, okjake commented on client/src/components/layouts/BeforeVisit/index.js
> +      <Typography varient="h5" gutterBottom>
variant

2020-07-08 08:38 UTC, okjake commented on client/src/components/layouts/BeforeVisit/index.js
> +          aria-label="meeting"
Including these accessibility labels is excellent

2020-07-08 08:42 UTC, okjake commented on client/src/components/layouts/BeforeVisit/index.js
> +    setMeeting(event.target.meeting);
I may be wrong but I think these might need to be `event.target.value`

2020-07-13 20:58 UTC, okjake commented on client/src/components/commonComponents/TabsCheckout/FormModel/checkoutFormModel.js
> +      requiredErrorMsg: 'Choose one of products at least',
'Choose at least one product'

2020-07-13 20:59 UTC, okjake commented on client/src/components/commonComponents/TabsCheckout/FormModel/validationSchema.js
> +    [covid19.name]: Yup.string().required("This Field is required"),
This field

2020-07-13 21:00 UTC, okjake commented on client/src/components/layouts/BeforeVisit/BeforeVisit.jsx
> +        What are you interested in viewing? select all that apply
Select

2020-07-13 21:01 UTC, okjake commented on client/src/components/layouts/BeforeVisit/BeforeVisit.jsx
> +        Have you been in contact within the last 14 days with anyone who has
any COVID symptoms

2020-07-13 21:04 UTC, okjake commented on client/src/components/layouts/BeforeVisit/Checkbox.jsx
> +      <React.Fragment>{renderHelperText()}</React.Fragment>
It doesn't really matter but this fragment isn't necessary

2020-07-13 21:04 UTC, okjake commented on client/src/components/layouts/BeforeVisit/Radio.jsx
> +      <React.Fragment>{renderHelperText()}</React.Fragment>
Same here

2020-07-13 21:28 UTC, Rahaf-96 requested changes

2020-07-13 21:28 UTC, Rahaf-96 commented on client/src/components/commonComponents/TabsCheckout/FormModel/validationSchema.js
> +// ).oneOf([true], 'Error'),
A comment! :open_mouth:

2020-07-13 21:28 UTC, Rahaf-96 commented on client/src/components/layouts/BeforeVisit/style.js
> +    // marginLeft: theme.spacing(3),
Another comment :open_mouth: HOW DARE YOU?

2020-07-14 09:45 UTC, Rahaf-96 approved these changes

2020-07-14 10:03 UTC, tasneembhiri approved these changes

2020-07-14 10:29 UTC, Jood80 commented on client/src/components/layouts/BeforeVisit/index.js
> +      <Typography varient="h5" gutterBottom>
Great Thanks!! I was trying to find out why the font is not responding to any changes I make. well here it is the reason :grin:

2020-07-14 10:29 UTC, Jood80 commented on client/src/components/layouts/BeforeVisit/index.js
> +    setMeeting(event.target.meeting);
yeah, you're right.
at first, it works that way but I believe it's more accurate to be `.value`

2020-07-14 10:29 UTC, Jood80 commented on client/src/components/layouts/BeforeVisit/BeforeVisit.jsx
> +        Have you been in contact within the last 14 days with anyone who has
GUESS WHATT!! I was in hurry to push that before 12:00 am like cinderella's clock :smirk: so yess, you are absolutely right. This has to be corrected in more than spelling I believe, even the naming has to be more descriptive..

2020-07-14 10:35 UTC, sara219 approved these changes

2020-07-14 10:37 UTC, merged