Component/landingpage
GSG-K3/urban-calendar pull request #58
Opened 2020-07-07 16:10 UTC by tasneembhiri

### create landing page    
### content
- [ ]  navbar
- [ ]  I added two picture
- [ ]  I added introduction 
- [ ]  I added Book Appointment Button 
- [ ] I added first style for desktop

2020-07-08 08:36 UTC, okjake commented
Nice start! I think you should take a look at the Grid component, it should help with the responsive layout

2020-07-08 14:13 UTC, sara219 requested changes

2020-07-08 14:13 UTC, sara219 commented on client/src/components/layouts/LandingPage/index.js
> +import footer from './footer.svg';
Add all the image into a dir called **(assets)**

2020-07-08 14:13 UTC, sara219 commented on client/src/components/layouts/LandingPage/style.js
> +      marginLeft: '-280px',
So much margin-left with a negative number!
maybe you can use top and right to handle the button position 

```
top: '2rem',
right: '18rem',
```

2020-07-08 14:13 UTC, sara219 commented on client/src/components/layouts/LandingPage/style.js
> +      justifyContent: 'space-around',
For the mobile view, can you make the description and button at the centre


![11](https://user-images.githubusercontent.com/47992412/86927218-bb6dfc00-c13b-11ea-969e-0e738b8aafb2.png)

2020-07-08 14:13 UTC, sara219 commented on client/src/components/layouts/LandingPage/index.js
> +                className={classes.button}
write a descriptive className

2020-07-09 09:24 UTC, sara219 approved these changes

2020-07-09 09:24 UTC, Rahaf-96 approved these changes
:woman_dancing: :partying_face:

2020-07-09 09:26 UTC, Jood80 approved these changes

2020-07-09 09:26 UTC, merged