Neating up/tabs checkout
GSG-K3/urban-calendar pull request #65
Opened 2020-07-09 20:57 UTC by Jood80

2020-07-11 10:08 UTC, okjake commented on client/src/components/layouts/ConfirmationTab/confirmationTab.jsx
> +      Our health and saftey rules
"safety"

2020-07-11 10:08 UTC, okjake commented on client/src/components/layouts/ConfirmationTab/confirmationTab.jsx
> +      3. Make sure to follow the American Red Cross Instuctions of Saftey.
Safety

2020-07-11 10:17 UTC, okjake commented
"_I've initiated each folder with a xxx.jsx file named with the component functionality and another index.js file
please let me know if we can change our file structure into this type or just staying at the one that we're using currently_"  I think this is fine to do, it makes your imports more concise and readable

2020-07-11 10:21 UTC, okjake requested changes
This looks good to me, there's just a couple of spelling mistakes with 'safety' - I saw that this came from the design work so we should consider it for the rest of the app too

We might want to do some small styling tweaks but I'd suggest we leave those to the end of the project and do them in one go after all the functionality is in

2020-07-11 19:47 UTC, Jood80 commented
> This looks good to me, there's just a couple of spelling mistakes with 'safety' - I saw that this came from the design work so we should consider it for the rest of the app too
> 
> We might want to do some small styling tweaks but I'd suggest we leave those to the end of the project and do them in one go after all the functionality is in

Alright :blush:

2020-07-12 08:35 UTC, sara219 approved these changes

2020-07-12 08:38 UTC, tasneembhiri approved these changes

2020-07-12 08:41 UTC, Rahaf-96 approved these changes

2020-07-12 13:32 UTC, merged